Repository Jaishree2310/GlassyUI-Components, pull requests merged in 2024-11, with the labels that each got.

#376 Light / Dark theme toggle button
  src/App.tsx
  src/components/AboutUsPage.tsx
  src/components/AccordionDetails.tsx
  src/components/AuthenticationCards.tsx
  src/components/BackToTopDetailsPage.tsx
  src/components/ButtonDetailsPage.tsx
  src/components/CardDetailsPage.tsx
  src/components/CheckboxDetails.tsx
  src/components/ContactUsDetailsPage.tsx
  src/components/ContributorsPage.tsx
  src/components/DonationPage.tsx
  src/components/DropdowndetailsPage.tsx
  src/components/Footer.tsx
  src/components/GalleryDetailsPage.tsx
  src/components/GlassMorphismGenrator.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/GlassyUILandingPage.tsx
  src/components/Header.tsx
  src/components/InputDetailPage.tsx
  src/components/ModalDetailsPage.tsx
  src/components/NavigationDetailsPage.tsx
  src/components/NotFoundPage.tsx
  src/components/PaginationDetails.tsx
  src/components/PopupDetailPage.tsx
  src/components/PricingDetailPage.tsx
  src/components/ProductCardDetailsPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/ScrollProgress.tsx
  src/components/SliderDetailsPage.tsx
  src/components/SpeedDialDetailsPage.tsx
  src/components/SpinnerDetailsPage.tsx
  src/components/StatisticDetails.tsx
  src/components/TestimonialDetails.tsx
  src/components/TextareaDetailPage.tsx
  src/components/ToastGenerator.tsx
  src/components/ToastPage.tsx
  src/components/TooltipDetailsPage.tsx
Labels: enhancement, gssoc-ext, Hacktoberfest, level3

#442 Added terms of use for glassy UI 🚀✨
  src/App.tsx
  src/components/Footer.tsx
  src/components/TermsOfUse.tsx
Labels: enhancement, gssoc-ext, level3

#437 fixes the 2 footer issues
  src/App.tsx
  src/components/Footer.tsx
Labels: enhancement, gssoc-ext, level2

#432 Added ai supported chatbot
  src/App.tsx
  src/components/AIChatbot.tsx
  src/components/BackToTop.tsx
Labels: enhancement, gssoc-ext, level3

#446 ✨ Added signup signin feature by google ✨
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/index.tsx
  src/login/SignIn.tsx
  src/login/SignUp.tsx
  src/login/UserAccount.tsx
  src/login/contexts/authContext/index.tsx
  src/login/firebase/auth.js
  src/login/firebase/firebase.js
Labels: enhancement, gssoc-ext, level2

#445 ✨ Added newsletter functionality to glassy ui ✨
  server/app.js
  server/controllers/newsletterController.js
  server/model/Newsletter.js
  server/routes/newsletterRoute.js
  server/sendSuscribedMail.js
  src/components/Footer.tsx
Labels: enhancement, gssoc-ext, level3

#447 Build frontend and Backend for Stories Page: Implement POST and GET Routes | clean schema✨🚀
  public/index.html
  server/app.js
  server/controllers/postsController.js
  server/model/postModel.js
  server/routes/storiesRoutes.js
  src/App.tsx
  src/components/Header.tsx
  src/components/Stories.tsx
Labels: enhancement, gssoc-ext, level3
