Repository Jaishree2310/GlassyUI-Components, pull requests merged in 2024-10, with the labels that each got.

#45 Made the bottom to top button
  src/components/BackToTop.tsx
  src/components/ButtonDetailsPage.tsx
  src/components/CardDetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/InputDetailPage.tsx
  src/components/PopupDetailPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/SpeedDialDetailsPage.tsx
  src/components/TextareaDetailPage.tsx
  src/components/TooltipDetailsPage.tsx
Labels: enhancement, good first issue, gssoc-ext

#42 Fixed the alignment of prop description section
  src/components/ButtonDetailsPage.tsx
  src/components/CardDetailsPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/SpeedDialDetailsPage.tsx
  src/components/TooltipDetailsPage.tsx
Labels: good first issue

#53 Fixes #46: Added Animation on the main page card Element
  src/components/GlassyUILandingPage.tsx
  src/index.css
Labels: gssoc-ext, level1

#68 title logo changed
  public/favicon.ico
  public/logo192.png
  public/logo512.png
Labels: good first issue, gssoc-ext, level1

#65 enhance color combinatin #55
  src/components/ButtonDetailsPage.tsx
  src/components/CardDetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/GlassyUILandingPage.tsx
  src/components/InputDetailPage.tsx
  src/components/ModalDetailsPage.tsx
  src/components/NotFoundPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/SpeedDial.tsx
  src/components/SpeedDialDetailsPage.tsx
  src/components/TextareaDetailPage.tsx
  src/components/TooltipDetailsPage.tsx
Labels: gssoc-ext, Hacktoberfest, level3

#75 created Husky setup
  .eslintignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  eslint.config.mjs
  package-lock.json
  package.json
Labels: enhancement, good first issue, gssoc-ext, level1

#84 Update Twitter logo
  src/components/GlassyUIComponentsPage.tsx
  src/components/SpeedDialDetailsPage.tsx
Labels: gssoc-ext, level1

#63 Make code structured in mobile view #56
  src/components/ButtonDetailsPage.tsx
  src/components/CardDetailsPage.tsx
  src/components/GlassMorphismGenrator.tsx
  src/components/InputDetailPage.tsx
  src/components/ModalDetailsPage.tsx
  src/components/PopupDetailPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/SpeedDialDetailsPage.tsx
  src/components/TextareaDetailPage.tsx
  src/components/TooltipDetailsPage.tsx
Labels: good first issue, gssoc-ext, Hacktoberfest, level1

#76 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level2

#89 Issue 50 add slider component to glassy UI
  src/App.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/SliderDetailsPage.tsx
Labels: gssoc-ext, level1

#93 aligned arrow icon
  src/components/GlassyUIComponentsPage.tsx
Labels: gssoc-ext, level1

#107 Glassy Authentication Cards Added Issue no #70 Resolved
  src/App.tsx
  src/components/AuthenticationCards.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: gssoc-ext, level2

#108 Change the Hero section and added animations and transitions
  package-lock.json
  package.json
  src/components/GlassyUILandingPage.css
  src/components/GlassyUILandingPage.tsx
  src/styled-jsx.d.ts
Labels: gssoc-ext, Hacktoberfest, level2

#102 Update package.json
  package.json
Labels: gssoc-ext, level1

#112 Fixes: #67: NEW TOAST COMPONENT
  src/App.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/Toast.tsx
  src/components/ToastGenerator.tsx
  src/components/ToastPage.tsx
  src/index.css
Labels: gssoc-ext, level2

#110 Navigation Bug Fixed
  src/components/NavigationDetailsPage.tsx
Labels: gssoc-ext, level1

#101 updated button text colour
  src/components/ButtonDetailsPage.tsx
Labels: gssoc-ext, level1

#100 added dropdown menu component
  src/App.tsx
  src/components/DropdowndetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, good first issue, gssoc-ext, level2

#114 added the docker
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: gssoc-ext, Hacktoberfest, level2

#113 Create badge
  src/components/badge.tsx
Labels: gssoc-ext, Hacktoberfest, level2

#96 Added the Contributors page super amazing and professional.
  package-lock.json
  package.json
  src/App.tsx
  src/components/ButtonDetailsPage.tsx
  src/components/ContributorsPage.tsx
  src/components/DropdowndetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/GlassyUILandingPage.tsx
Labels: good first issue, gssoc-ext, level2

#129 Fixing bottom spacing of Glossy text
  src/components/GlassyUILandingPage.css
Labels: enhancement, gssoc-ext, level2

#126 update App.css
  src/App.css
Labels: good first issue, gssoc-ext, level1

#122 Added AboutUs Page
  package-lock.json
  src/App.tsx
  src/components/AboutUsPage.tsx
  src/components/Header.tsx
Labels: enhancement, gssoc-ext, Hacktoberfest, level3

#99 Added back to top button
  src/App.tsx
  src/components/BackToTopDetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: good first issue, gssoc-ext, level1

#57 added cursor-animation
  src/App.tsx
  src/index.css
Labels: gssoc-ext, Hacktoberfest, level2

#135 added gsap animation to homepage fixes #117
  package-lock.json
  package.json
  src/components/GlassyUILandingPage.tsx
  src/components/Header.tsx
Labels: enhancement, gssoc-ext, level1

#98 Added pricing page component
  src/App.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/PricingDetailPage.tsx
Labels: enhancement, good first issue, gssoc-ext, level2

#144 Update website preview section in README file to reflect new UI changes
  README.md
Labels: good first issue, gssoc-ext, level1

#160 Paging
  package-lock.json
  package.json
  src/components/AboutUsPage.tsx
  src/components/DonationPage.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, gssoc-ext, level2

#143 Added photos of all contributors fixes #133
  README.md
Labels: gssoc-ext, level1

#145 Add Searchbar Component
  package-lock.json
  package.json
  src/App.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/SearchbarDetails.tsx
Labels: enhancement, gssoc-ext, level3

#163 Fix visibility issue in glassmorphism generator component
  src/components/GlassMorphismGenrator.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: gssoc-ext, Hacktoberfest, level3

#165 ADDING a CHANGELOG Section in README file
  README.md
Labels: good first issue, gssoc-ext, level1

#155 Added Testimonial section
  README.md
  src/App.tsx
  src/components/CardDetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/GlassyUILandingPage.tsx
  src/components/ModalDetailsPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/TestimonialDetails.tsx
  src/components/TextareaDetailPage.tsx
  src/components/TooltipDetailsPage.tsx
  src/index.css
Labels: enhancement, gssoc-ext, level3

#154 Added pagination
  src/App.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/PaginationDetails.tsx
Labels: enhancement, gssoc-ext, level2

#168 fixed progress bar width in mobile view
  src/components/GlassyUIComponentsPage.tsx
  src/components/ProgressBarDetailPage.tsx
Labels: enhancement, gssoc-ext, level2

#176 ADDING ROADMAP IN README
  README.md
Labels: good first issue, gssoc-ext, level2

#183 Fix table and title format across all the components to maintain uniformity
  src/components/AccordionDetails.tsx
  src/components/AuthenticationCards.tsx
  src/components/BackToTopDetailsPage.tsx
  src/components/ButtonDetailsPage.tsx
  src/components/DropdowndetailsPage.tsx
  src/components/GlassMorphismGenrator.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/InputDetailPage.tsx
  src/components/ModalDetailsPage.tsx
  src/components/NavigationDetailsPage.tsx
  src/components/PaginationDetails.tsx
  src/components/PopupDetailPage.tsx
  src/components/PricingDetailPage.tsx
  src/components/ProgressBarDetailPage.tsx
  src/components/SliderDetailsPage.tsx
  src/components/SpeedDialDetailsPage.tsx
  src/components/TestimonialDetails.tsx
  src/components/TextareaDetailPage.tsx
  src/components/ToastPage.tsx
  src/components/TooltipDetailsPage.tsx
Labels: enhancement, gssoc-ext, level3

#178 added search functionality
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, gssoc-ext, level2

#173 improve card page title visibilty
  src/components/CardDetailsPage.tsx
Labels: enhancement, gssoc-ext, level2

#141 Added contact us page
  README.md
  src/App.tsx
  src/components/ContactUsDetailsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, gssoc-ext, Hacktoberfest, level3

#182 solved issue #78
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Footer.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, gssoc-ext, level2

#157 Adding a About us page
  package-lock.json
  package.json
  src/components/AboutUsPage.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, gssoc-ext, level2

#191 changed donation page ui
  src/components/DonationPage.tsx
Labels: gssoc-ext, level2

#238 Fix pagination
  .github/workflows/greetings.yml
  README.md
  src/components/AboutUsPage.tsx
  src/components/ContributorsPage.tsx
  src/components/Footer.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: gssoc-ext, level2

#245 Google translator added
  src/components/Footer.tsx
  src/components/GoogleTranslator.jsx
Labels: enhancement, gssoc-ext, level3

#207 ADD GSSOC AND HACKTOBERFEST BANNER ON THE README
  Images/212284100-561aa473-3905-4a80-b561-0d28506553ee.gif
  Images/329829127-e79eb6de-81b1-4ffb-b6ed-f018bb977e88.png
  Images/Image
  Images/hacktober.png
  README.md
Labels: gssoc-ext, level1

#184 Added Chatbot
  public/index.html
Labels: enhancement, gssoc-ext, level3

#192 add paging in contributor page
  src/components/ContributorsPage.tsx
Labels: enhancement, good first issue, gssoc-ext, level2

#219 Add Checkbox Glassy Component
  package-lock.json
  src/App.tsx
  src/components/Checkbox.tsx
  src/components/CheckboxDetails.tsx
  src/components/GlassyUIComponentsPage.tsx
Labels: enhancement, gssoc-ext, Hacktoberfest, level3

#256 Remove footer from when clicking on the components
  README.md
  package-lock.json
  src/App.tsx
  src/components/AboutUsPage.tsx
  src/components/ContributorsPage.tsx
  src/components/GlassyUILandingPage.css
  src/components/GlassyUILandingPage.tsx
Labels: enhancement, good first issue, gssoc-ext, level2

#302 Added animation !!
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/CheckboxDetails.tsx
  src/components/ContributorsPage.tsx
  src/components/Footer.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/GlassyUILandingPage.tsx
  src/components/ProductCardDetailsPage.tsx
  src/index.css
  tailwind.config.js
Labels: enhancement, gssoc-ext, level3

#294 Corrected the order of Modal component
  src/App.tsx
  src/components/CheckboxDetails.tsx
  src/components/Footer.tsx
  src/components/GlassyUIComponentsPage.tsx
  src/components/GlassyUILandingPage.tsx
  src/components/ModalDetailsPage.tsx
Labels: enhancement, help wanted, gssoc-ext, Hacktoberfest, level3

#326 Corrected the order of speed dial component
  README.md
  src/components/GlassyUIComponentsPage.tsx
  src/components/SpeedDialDetailsPage.tsx
Labels: enhancement, gssoc-ext, level3
